import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tailwind',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-screen h-screen flex items-center justify-center'>
        <div className='w-[1000px] h-[500px] bg-bg-image'>
          <div className='border-[20px] rounded-xl border-sky-400 outline outline-1 w-[85%] h-[85%] relative top-6 left-5'>
          {/* <div className='w-full h-full bg-white rounded-xl'>
          </div> */}
        {children}
          </div>
        </div>
      </body>
    </html>
  )
}
